
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
      - SECRET_KEY=django-insecure-j3paouk-idbpdb&^qt8ucc1_+!#6_4uc95c2%d@2gs70yc8ifz
      - DEBUG=False
    depends_on:
      - redis

  worker:
    build: .
    container_name: worker
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
    environment:
      - SECRET_KEY=django-insecure-j3paouk-idbpdb&^qt8ucc1_+!#6_4uc95c2%d@2gs70yc8ifz
      - DEBUG=False
    depends_on:
      - redis
      - backend

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    depends_on:
      - redis
      - backend

volumes:
  static_volume:
  media_volume: